### ISSUE TITLE
readxlsheet reads the empty cells as #NA 

### ISSUE THREAD

**Issue by ezgikurt** [queryverse/ExcelReaders.jl#57]
Hi, I'm using Julia 0.6.4, with version 0.9.0. This used to work fine in the earlier versions but I've recently updated the package to 0.9 and now readxlsheet reads the empty cells in the file as "#NA" and julia does not register this as a missing value. typeof() returns DataValue(Union{})(). 

I need these to register as missing values, are there any suggestions?

**Comment by davidanthoff** [comment]
I don't think anything changed there? What behavior would you expect?

**Comment by ezgikurt** [comment]
They used to be registered as "missing", and functions such as ismissing() returned true (now they return false).

**Comment by davidanthoff** [comment]
Ah, I think you were reading them into a ``DataFrame``, right? That functionality has been moved from this package to [ExcelFiles.jl](https://github.com/queryverse/ExcelFiles.jl), and if you materialize things into a ``DataFrame`` that way, you'll get ``missing`` values for empty cells.

I don't think this package here ever created ``missing`` values, though...

**Comment by ezgikurt** [comment]
That's the case with ExcelFiles,but I usually used ExcelReaders like so and it did create missings (NAs in earlier versions of DataArrays).

a = readxlsheet(filename, sheetname);

a would come back as a DataArray{Any,2} with missings, and we did not pre-allocate it.

**Comment by davidanthoff** [comment]
Ah, interesting! I guess what happened is that ``DataArray`` was ported to ``Missing`` at some point, and then all of a sudden ExcelReaders.jl returned ``missing`` values, even though I was not even aware of that :)

The Queryverse is not using the whole ``Missing`` story. That design doesn't work for some key scenarios due to some technical limitations, so Queryverse is using [DataValues.jl](https://github.com/queryverse/DataValues.jl) for its missing value story, and that is what you are getting there.

**Comment by ezgikurt** [comment]
Oh all right, thanks for the responses! Going forward I'm going to have to use ExcelFiles I guess.
